name: tibia_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  bonfire: ^3.16.1
  cupertino_icons: ^1.0.8
  # Se você quer a 1.35.0, coloque-a aqui diretamente
  flame: 1.35.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Movido para cá (onde deve ficar)
  flutter_lints: ^5.0.0 

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/player/
    - assets/images/map/
    - assets/images/enemies/rat/
    - assets/images/enemies/cyclops/
    - assets/images/enemies/troll/